### PR TITLE
Add LimitedTextarea

### PR DESCRIPTION
**Pull request by Chalarangelo**
A simple `<textarea>` with a character limit (similar to Twitter's input):

- Uses `state`.
- Handles the `onChange` event.

### CODE REVIEW

**Comment by meetzaveri** [comment]
@Chalarangelo You forget to add extension to the file as `.md` i.e. to markdown. Please convert file with extension

**Comment by Chalarangelo** [comment]
@meetzaveri Good catch, thanks! 😅

**Comment by Chalarangelo** [comment]
@fejes713 Absolutely. We want a `linter` in this repo, too. If you want, you can get started on that as soon as you have time (or the builder or any other script we need - currently I suspect `build`, `lint`, `tag`, `web`).

**Comment by fejes713** [comment]
Challenge accepted 👍 I'll work on scripts during my Uni classes then 😄

**Comment by skatcat31** [comment]
I think tomorrow I might have some time to test these with a JSX compiler. If it works as intended I'll give a LGTM

**Comment by skatcat31** [comment]
woof has my time got me forgetting... I'll look at this tomorrow while awaiting feedback

**Comment by Chalarangelo** [comment]
@skatcat31 Testing it right now, it seems to work and the only issue was formatting the code snippet. I think we can safely merge soon.

**Pull request merged**
